[package]
name = "clap_play"
version = "0.1.0"
authors = ["Mike Burr <mb@unintuitive.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
