[package]
name = "cbor_play"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_cbor = "0.11.1"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.126"
