[package]
name = "crates_io_api_play"
version = "0.1.0"
authors = ["Mike Burr <mb@unintuitive.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crates_io_api = "0.7.2"
