[package]
name = "transport_http"
version = "0.1.0"
authors = ["Mike Burr <mb@unintuitive.org>"]
edition = "2018"

[dependencies]
web3 = "0.15.0"
tokio = { version = "1", features = ["full"] }
hex-literal = "0.3.1"
