[package]
name = "abandoned-addresses"
version = "0.0.1"
authors = ["Mike Burr <mb@unintuitive.org>"]
edition = "2018"
description = "Interact with the abandoned-addresses contract from Rust"

[dependencies]
ethers = "0.2.2"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
