[package]
name = "ethers_play"
version = "0.1.0"
authors = ["mburr"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "0.2.2"